# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletable',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sampletable',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
